- name: Install graphviz
  apt:
    name:
      - graphviz
      - graphviz-dev
    update_cache: true
  become: true

- name: Install caret dependent packages
  pip:
    requirements: "{{ requirements_path }}"
    executable: pip3
    extra_args: --break-system-packages
  become: false
  args:
    chdir: "{{ WORKSPACE_ROOT }}"
